services:
  - type: web
    name: smart-ai-resume-checker-backend
    env: python
    buildCommand: pip install -r requirements.txt && npm install
    startCommand: node server.js
    rootDir: Backend
    envVars:
      - key: PORT
        value: 10000
