services:
  - type: web
    name: smart-ai-resume-checker-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
    rootDir: Backend
    plan: free
